# Generated by Django 3.2.5 on 2021-07-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('type_of_content', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('links', models.CharField(max_length=40)),
                ('Video_content', models.FileField(blank=True, upload_to='video/%y')),
            ],
        ),
    ]
