# Generated by Django 3.2.5 on 2021-10-02 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afro', '0003_alter_usersetting_verification_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='verification_expires',
            field=models.DateField(default=datetime.date(2021, 10, 5)),
        ),
    ]
